### PR TITLE
Added interfaces for sending and recieving for subsystem use, added multiple message types (Command && Data)

### PR DESCRIPTION
**Pull request by s-axford**
Lots of other code fixes detailed in other PR's such as timeout issues, flattening issues, static value cleanup etc

We can discuss these changes and the code structure in our meeting later this week

MAJOR UPDATE
API CHANGES:
-Added reply functionality
-added MessageSenderInterface and MessageRecievingInterface for creating API's for subsystems
-Created MessageSendingService and MessageRecievingService as API's for subsystems
-Fixed socket read timeout
-Added acknowledgment functionality
-Added string as possible value in key value pairs
-Added functionality for allowing repositories to reply to clients which are requesting data they contain
-Added "Phonebook" for subsystem identifier lookups
-Changed message capacity to a setting (was hard-coded)
-All UnixDomainStreamSocketClient operations are now handled by MessageSendingService or LorisMessager
-All UnixDomainStreamSocketServer operations are now handled by MessageReceivingService
-Repositories now have a run loop in the form of the start() method.
-Split Message class into CommandMessage or DataMessage (More message types can be created by using Message as an Interface)
-All receiving processes operate with pointers to Message objects, for DataMessage or CommandMessage specific actions dynamic_casts can be done to ensure proper type handling
-Information about different message types and their serialized forms can be found in their header files 

High level compilation instructions:
Compile internal-messaging first and include all .h files in the internal-messaging directory
Compile core by linking internal-messaging as a library, adding all .h files in the core directory and all .h files in the internal-messaging directory
Compiling emulation should be the same as compiling core 

Subsystems should use internal-messaging for their messaging needs and can use emulation as an example of sending/receiving messages. core currently contains the code for running repositories.

### CODE REVIEW

**Comment by liamhebert** [comment]
No way, am I dreaming or is this the develop into master merge I’ve been hoping for all this time! Can’t wait to dig into this one!

**Comment by amellalalex** [comment]
Looks great upfront! I will take a closer look asap

**Comment by s-axford** [comment]
Yes Liam! I figured if there are new people looking at the codebase they might as well be using the newest code. This PR can also serve as a good method to address any interface concerns, or question about the codebase.

**Comment by amellalalex** [comment]
I've been able to compile the whole repo beautifully so I don't see any reason not to merge this branch to the master! 

My only question at the moment would be how to structure the command to run the core executable.

Thanks in advance!

**Comment by s-axford** [comment]
@amellalalex Perfect! the core program currently runs a single repository (server for messages to be received from subsystems for those who don't know). When you run the program you need to specify which repository you wish to start. The list is as below:
```
switch(option_number){
			case 1 : StartPowerRepository(); break;
			case 2 : StartPayloadRepository(); break;
			case 3 : StartGpsRepository(); break;
			case 4 : StartCommsRepository(); break;
			case 5 : StartAdcsRepository(); break;
			default : cout << "Invalid argument" << endl; break;
			return 1;
}

```
so to run the power repository you would run ./core 1
or to run the payload repository (camera) you would run ./core 2, etc

I think we should merge in #37 before merging this because it will prove extremely valuable to new members. Additionally I will rebase this branch onto master to ensure the commit log lines up cleanly.

**Pull request merged**
